name: Maven Test

on:
  pull_request: {branches: master}

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      working-directory: ./App
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with maven
        run: mvn -B package --file pom.xml
        working-directory: ${{env.working-directory}}
      - name: Artifact
        working-directory: ${{env.working-directory}}
        run: mkdir artifact && cp target/*.jar artifact && cp .env artifact && cp -r target/lib artifact
      - name: Test 
        run: mvn test
        working-directory: ${{env.working-directory}}
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: ${{env.working-directory}}/artifact